MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/mnt/nas_crdataset/models/mrcnn_model/kitti/model_0004000.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 11
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True

DATASETS:
  TRAIN: ("kitti_instance_train",)
  TEST: ("kitti_instance_train",) #TEST: ("kitti_instance_test",)

INPUT:
#  MIN_SIZE_TRAIN: 800
#  MAX_SIZE_TRAIN: 1242
#  MAX_SIZE_TEST:  1242
  MIN_SIZE_TRAIN: 800
  MAX_SIZE_TRAIN: 2048
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 2048

DATALOADER:
  SIZE_DIVISIBILITY: 32

SOLVER:
  WEIGHT_DECAY: 0.0001
  STEPS: (3000, )
  MAX_ITER: 4000
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
  CHECKPOINT_PERIOD: 200

TEST:
  IMS_PER_BATCH: 4
